version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_oee_collector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oee_collector
    volumes:
          - data-oee-collector:/var/lib/postgresql/data/
volumes:
  data-oee-collector:
